# Generated by Django 4.1 on 2022-08-24 04:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import goods.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, max_length=512)),
                ("sales", models.PositiveIntegerField(default=0)),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("color", models.CharField(blank=True, max_length=16)),
                ("cpu", models.CharField(blank=True, max_length=16)),
                ("memory", models.CharField(blank=True, max_length=16)),
                ("hard_disk", models.CharField(blank=True, max_length=16)),
                ("graphics_card", models.CharField(blank=True, max_length=16)),
                (
                    "time_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods",
                        related_query_name="goods",
                        to="goods.brand",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "brand",
                        "name",
                        "color",
                        "cpu",
                        "memory",
                        "hard_disk",
                        "graphics_card",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to=goods.models.path_and_rename)),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        related_query_name="picture",
                        to="goods.goods",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="brand",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                related_query_name="brand",
                to="goods.category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="brand",
            unique_together={("category", "name")},
        ),
    ]
