# Generated by Django 4.1 on 2022-08-23 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="add_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
