# Generated by Django 4.1 on 2022-08-24 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("receiving_address", "0001_initial"),
        ("goods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TO_BE_PAID", "待付款"),
                            ("TO_BE_SHIPPED", "待发货"),
                            ("TO_BE_RECEIVED", "待收货"),
                            ("COMPLETED", "已完成"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="TO_BE_PAID",
                        max_length=128,
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("time_paid", models.DateTimeField(blank=True, null=True)),
                ("time_shipped", models.DateTimeField(blank=True, null=True)),
                ("time_received", models.DateTimeField(blank=True, null=True)),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods",
                        related_query_name="goods",
                        to="goods.goods",
                    ),
                ),
                (
                    "receiving_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="receiving_address.receivingaddress",
                        verbose_name="收货信息",
                    ),
                ),
                (
                    "related_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        related_query_name="order",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
